---
# tasks file for cs_studio_phoebus
- name: Clone and/or update the phoebus repo
  become: true
  git:
    repo: "https://github.com/ControlSystemStudio/phoebus.git"
    dest: /opt/epics-tools/lib/phoebus
    version: "{{ phoebus_version }}"
    force: true
  register: phoebus_repo

- name: Build the documentation and help
  command: mvn clean verify -P sphinx -N
  become: true
  args:
    chdir: /opt/epics-tools/lib/phoebus/
  environment:
    JAVA_HOME: "{{ java_home }}"
    MVN_HOME: "{{ mvn_home }}"
    PATH: "{{ java_home }}/bin:{{ mvn_home }}/bin:{{ ansible_env.PATH }}"
  when: phoebus_repo.changed | bool

- name: Build the common phoebus binaries (this may take a while)
  command: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true
  become: true
  args:
    chdir: /opt/epics-tools/lib/phoebus/
  environment:
    JAVA_HOME: "{{ java_home }}"
    MVN_HOME: "{{ mvn_home }}"
    PATH: "{{ java_home }}/bin:{{ mvn_home }}/bin:{{ ansible_env.PATH }}"
  when: phoebus_repo.changed | bool

- name: ensure config directory exists for phoebus
  become: true
  file:
    path: /opt/epics-tools/config
    state: directory
    owner: "{{ epics_services_account }}"
    group: "{{ epics_services_account }}"

- name: create phoebus preferences
  become: true
  template:
    src: preferences.ini.j2
    dest: /opt/epics-tools/config/preferences.ini
    mode: 0755
    owner: "{{ phoebus_owner }}"
    group: "{{ phoebus_owner }}"

- name: create phoebus logging properties
  become: true
  template:
    src: logging.properties.j2
    dest: /opt/epics-tools/config/logging.properties
    mode: 0755
    owner: "{{ phoebus_owner }}"
    group: "{{ phoebus_owner }}"

- name: create run-phoebus wrapper
  become: true
  template:
    src: run-phoebus.sh.j2
    dest: /usr/local/bin/run-phoebus
    mode: 0755
    owner: "{{ phoebus_owner }}"
    group: "{{ phoebus_owner }}"
